[package]
name = "ember-lox-parse"
version = "0.1.0"
edition = "2021"

[dependencies.ember-lox-tokenizer]
path = "../ember-lox-tokenizer"

[dependencies.ember-lox-ast]
path = "../ember-lox-ast"

[dependencies.macros]
path = "../macros"
