[package]
name = "ember-lox-ast"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.ember-lox-rt]
path = "../ember-lox-rt"

[dependencies.ember-lox-tokenizer]
path = "../ember-lox-tokenizer"
